//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.03 at 03:38:41 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cbrl.com/soap/service/example/vehicle/domain", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cbrl.soap.service.example.vehicle.domain;
